version: '3'

services:
  web:
    build: .
    command: python /testpro/manage.py migrate
    command: python /testpro/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/testpro
    ports:
      - 8000:8000
