# Generated by Django 2.2.6 on 2019-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_number',
            new_name='number',
        ),
    ]
